# Sử dụng PHP 8.2 với Apache làm base image
FROM php:8.2-apache

# Kích hoạt module rewrite của Apache
RUN a2enmod rewrite

# Thiết lập thư mục làm việc mặc định
WORKDIR /var/www/html

# Sao chép mã nguồn vào thư mục của Apache
COPY . /var/www/html/

# Cấp quyền truy cập cho Apache
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Expose cổng 80 để truy cập web
