# Sử dụng Python 3.9 làm base image
FROM python:3.9

# Đặt thư mục làm việc
WORKDIR /app

# Copy file vào container
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Mở cổng 5000
EXPOSE 5000

# Chạy ứng dụng
CMD ["python", "app.py"]
