# Stage 1: Build ứng dụng với node:18
FROM node:18 as builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Chạy ứng dụng với node:18-alpine
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app /app
CMD ["node", "server.js"]
