# Sử dụng Redis latest làm base image
FROM redis:latest

# Sao chép file cấu hình vào container
COPY redis.conf /usr/local/etc/redis/redis.conf

# Chạy Redis với file cấu hình đã tùy chỉnh
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# Mở cổng 6379
EXPOSE 6379
